{
    "query": "遇到PyTorch版本不匹配导致CUDA不可用的问题，请给出解决方案。",
    "summaries": [
        "云主机中遇到PyTorch版本不匹配导致CUDA不可用的问题。通过创建新的conda环境，安装指定版本的PyTorch（1.12.1）、torchvision（0.13.1）和torchaudio（0.12.1），并使用CUDA Toolkit 11.6解决该问题。安装后测试成功，CUDA可用。",
        "TIB-GPU系统在安装PyTorch包时出现CondaVerificationError和ClobberError错误。主要问题包括多个CUDA库（如libcusolver、libnpp）的包损坏，表现为文件路径缺失或文件大小不匹配。同时，由于不同包共享相同路径（如bin/cjpeg、bin/djpeg），导致ClobberError。解决方法可能涉及清理缓存、重新下载包或调整环境配置。",
        "系统显示NVIDIA A100 GPU卡的CUDA版本为11.4，但使用CUDA 10.2的PyTorch时出现不兼容警告。建议安装与CUDA 11.3兼容的PyTorch 1.10.1版本，通过conda安装命令完成安装。"
    ],
    "contents": [
        "path 'lib/libnppicc.so.12'\nspecified in the package manifest cannot be found.\nCondaVerificationError: The package for libnpp located at /hpcfs/fhome/yangjh4/.conda/pkgs/libnpp-12.0.2.50-0\nappears to be corrupted. The path 'lib/libnppidei.so.12'\nspecified in the package manifest cannot be found.\nCondaVerificationError: The package for libnpp located at /hpcfs/fhome/yangjh4/.conda/pkgs/libnpp-12.0.2.50-0\nappears to be corrupted. The path 'lib/libnppif.so.12'\nspecified in the package manifest cannot be found.\nCondaVerificationError: The package for libnpp located at /hpcfs/fhome/yangjh4/.conda/pkgs/libnpp-12.0.2.50-0\nappears to be corrupted. The path 'lib/libnppif.so.12.0.2.50'\nspecified in the package manifest cannot be found.\nCondaVerificationError: The package for libnpp located at /hpcfs/fhome/yangjh4/.conda/pkgs/libnpp-12.0.2.50-0\nappears to be corrupted. The path 'lib/libnppig.so.12'\nspecified in the package manifest cannot be found.\nSafetyError: The package for libnpp located at /hpcfs/fhome/yangjh4/.conda/pkgs/libnpp-12.0.2.50-0\nappears to be corrupted. The path 'lib/libnppig.so.12.0.2.50'\nhas an incorrect size.\nreported size: 39811936 bytes\nactual size: 9912320 bytes\nCondaVerificationError: The package for libnpp located at /hpcfs/fhome/yangjh4/.conda/pkgs/libnpp-12.0.2.50-0\nappears to be corrupted. The path 'lib/libnppim.so.12'\nspecified in the package manifest cannot be found.\nCondaVerificationError: The package for libnpp located at /",
        "The following packages will be downloaded:\npackage                    |            build\nffmpeg-4.3                 |       hf484d3e_0         9.9 MB  pytorch\ngnutls-3.6.15              |       he1e5248_0         1.0 MB\njpeg-9d                    |       h7f8727e_0         232 KB\nlame-3.100                 |       h7b6447c_0         323 KB\nlibtasn1-4.16.0            |       h27cfd23_0          58 KB\nlibunistring-0.9.10        |       h27cfd23_0         536 KB\nlibuv-1.40.0               |       h7b6447c_0         736 KB\nmkl-service-2.4.0          |   py39h7f8727e_0          59 KB\nmkl_fft-1.3.1              |   py39hd3c417c_0         182 KB\nmkl_random-1.2.2           |   py39h51133e4_0         309 KB\nnumpy-1.21.2               |   py39h20f2e39_0",
        "Usage      |\n||\n|  No running processes found                                                 |\n++\n可以看到系统A100GPU卡的CUDA版本为11.4，当使用cuda为10.2的pytorch时会出现一下报错：\n/fs1/home/wuqi/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/cuda/init.py:104: UserWarning:\nNVIDIA A100 80GB PCIe with CUDA capability sm_80 is not compatible with the current PyTorch installation.\nThe current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.\nIf you want to use the NVIDIA A100 80GB PCIe GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/\nwarnings.warn(incompatible_device_warn.format(device_name, capability, \" \".join(arch_list), device_name))\n使用conda安装pytorch-1.10.1-cuda11.3版本\n(pytorch) [wuqi@th-hpc4-ln0 transformer]$ conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch\nCollecting package metadata (current_repodata.json): done\nSolving environment: done\n## Package Plan ##\nenvironment location: /fs1/home/wuqi/anaconda3/envs/pytorch\nadded / updated specs:\n- cudatoolkit=11.3\n- pytorch\n- torchaudio\n- torchvision\nThe following packages will be downloaded:\npackage                    |            build\nffmpeg",
        "80994MiB |      0%      Default |\n|                               |                      |             Disabled |\n++++\n|   1  NVIDIA A100 80G...  Off  | 00000000:4B:00.0 Off |                    0 |\n| N/A   47C    P0    68W / 300W |      0MiB / 80994MiB |      0%      Default |\n|                               |                      |             Disabled |\n++++\n++\n| Processes:                                                                  |\n|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |\n|        ID   ID                                                   Usage      |\n||\n|  No running processes found",
        "Anaconda, Inc. on linux\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n>>> import torch\n>>> torch.cuda.is_available()\nTrue",
        "【已解决】TIB-GPU系统pytorch包CondaVerificationError、ClobberError错误\n**标签**: ClobberError\n**创建时间**: 2024-07-19 16:39:53\n**更新时间**: 2024-07-19 16:39:53\n**作者**: 杜佳伟\nownloading and Extracting Packages\nPreparing transaction: done\nVerifying transaction: failed\nCondaVerificationError: The package for libcusolver located at /hpcfs/fhome/yangjh4/.conda/pkgs/libcusolver-11.4.4.55-0\nappears to be corrupted. The path 'lib/libcusolver.so.11.4.4.55'\nspecified in the package manifest cannot be found.\nSafetyError: The package for libcusolver located at /hpcfs/fhome/yangjh4/.conda/pkgs/libcusolver-11.4.4.55-0\nappears to be corrupted. The path 'lib/libcusolverMg.so.11.4.4.55'\nhas an incorrect size.\nreported size: 194249232 bytes\nactual size: 155926528 bytes\nCondaVerificationError: The package for libnpp located at /hpcfs/fhome/yangjh4/.conda/pkgs/libnpp-12.0.2.50-0\nappears to be corrupted. The path 'lib/libnppc.so.12'\nspecified in the package manifest cannot be found.\nCondaVerificationError: The package for libnpp located at /hpcfs/fhome/yangjh4/.conda/pkgs/libnpp-12.0.2.50-0\nappears to be corrupted. The path 'lib/libnppial.so.12'\nspecified in the package manifest cannot be found.\nCondaVerificationError: The package for libnpp located at /hpcfs/fhome/yangjh4/.conda/pkgs/libnpp-12.0.2.50-0\nappears to be corrupted. The path 'lib/libnppicc.so.12'\nspecified in the package manifest cannot be found.\nCondaVerificationError: The package for libnpp located at /hpcfs/fhome/yangjh4/",
        "【已解决】云主机torch版本不对应的问题\n**标签**: 无标签\n**创建时间**: 2023-12-27 15:42:25\n**更新时间**: 2023-12-27 15:42:25\n**作者**: 李淑宁\n[GCC 11.2.0] :: Anaconda, Inc. on linux\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n>>> import torch\n>>> torch.cuda.is_available()\n/root/miniconda3/lib/python3.8/site-packages/torch/cuda/init.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11030). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)\nreturn torch._C._cuda_getDeviceCount() >\nFalse\n>>>\n1.解决报错\nconda create -n torch1.12 python=3.8\nconda activate torch1.12\nconda install pytorch1.12.1 torchvision0.13.1 torchaudio0.12.1 cudatoolkit=11.6 -c pytorch -c conda-forge\n2.测试成功\n(torch1.12) [root@bogon ~]# python\nPython 3.8.18 (default, Sep 11 2023, 13:40:15)\n[GCC 11.2.0] :: Anaconda, Inc. on linux\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n>>> import torch\n>>",
        "be corrupted. The path 'lib/libnppim.so.12'\nspecified in the package manifest cannot be found.\nCondaVerificationError: The package for libnpp located at /hpcfs/fhome/yangjh4/.conda/pkgs/libnpp-12.0.2.50-0\nappears to be corrupted. The path 'lib/libnppist.so.12'\nspecified in the package manifest cannot be found.\nCondaVerificationError: The package for libnpp located at /hpcfs/fhome/yangjh4/.conda/pkgs/libnpp-12.0.2.50-0\nappears to be corrupted. The path 'lib/libnppisu.so.12'\nspecified in the package manifest cannot be found.\nCondaVerificationError: The package for libnpp located at /hpcfs/fhome/yangjh4/.conda/pkgs/libnpp-12.0.2.50-0\nappears to be corrupted. The path 'lib/libnppitc.so.12'\nspecified in the package manifest cannot be found.\nCondaVerificationError: The package for libnpp located at /hpcfs/fhome/yangjh4/.conda/pkgs/libnpp-12.0.2.50-0\nappears to be corrupted. The path 'lib/libnpps.so.12'\nspecified in the package manifest cannot be found.\nClobberError: This transaction has incompatible packages due to a shared path.\npackages: defaults/linux-64::jpeg-9e-h5eee18b_1, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0\npath: 'bin/cjpeg'\nClobberError: This transaction has incompatible packages due to a shared path.\npackages: defaults/linux-64::jpeg-9e-h5eee18b_1, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0\npath: 'bin/djpeg'\nClobberError: This transaction has incompatible packages due to a shared path.\npackages: defaults/linux-64"
    ]
}